# Generated by Django 4.1.5 on 2023-04-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_mymodels_delete_item_delete_todolist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyModels",
            new_name="Note",
        ),
    ]
