# Generated by Django 4.1.5 on 2023-05-08 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_notes_options_remove_notes_complete_noteapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteapp",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="noteapp",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
