# Generated by Django 4.1.5 on 2023-05-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_description_task_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="noteapp",
            old_name="description",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="content",
            new_name="description",
        ),
    ]
