# Generated by Django 4.1.5 on 2023-05-28 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remainder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remainder",
            name="date_time",
        ),
        migrations.AddField(
            model_name="remainder",
            name="date",
            field=models.DateField(default=datetime.date(2023, 5, 28)),
        ),
        migrations.AddField(
            model_name="remainder",
            name="time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
